language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs-v2"
  - "iojs-v3"
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: false
